name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 82.198.228.57
          username: u162093132
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script_stop: true
          script: |
            # 1. الدخول للمجلد الصحيح للمشروع الحالي
            cd ~/domains/shaghafgifts2.com/public_html

            # 2. تحديث الكود
            git fetch origin main
            git reset --hard origin/main

            # 3. تحديث المكتبات والتهجير (ضروري جداً)
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force

            # 4. تنظيف الكاش لضمان ظهور التعديلات
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
